import type { Metadata } from "next";
import "./globals.css";
import { Recursive } from '@next/font/google'
import { Toaster } from "react-hot-toast"

const font = Recursive({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Caseify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className={font.className}>
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          containerClassName=""
          containerStyle={{}}
          toastOptions={{
            duration: 2000,
          }}
        />
      </body>
    </html>
  );
}
